<?php $pageTitle = 'Frequently Asked Questions'; require_once __DIR__ . '/includes/config.php'; require_once __DIR__ . '/includes/header.php'; ?>
<section class="page-hero content-hero faq-hero"><div class="container"><div class="section-tag">Help centre</div><h1>Questions about your <span class="accent">movie night.</span></h1><p>Clear answers about accounts, profiles, reservations, payments, tickets, cancellations, rewards and cinema operations.</p></div></section>
<section class="section"><div class="container faq-layout"><aside class="faq-index reveal-cinema"><div class="section-tag">Browse topics</div><a href="#accounts">Accounts & profiles</a><a href="#reservations">Seats & reservations</a><a href="#checkout">Cart & checkout</a><a href="#tickets">Tickets & bookings</a><a href="#rewards">Rewards & offers</a></aside><div class="faq-groups">
<section id="accounts" class="faq-group reveal-cinema"><div class="section-tag">Accounts & profiles</div><details open><summary>How do I create and complete my profile?</summary><p>Register with your name, username, email and password. MoviePro then opens Profile, where you can upload a picture, add your city, choose genres and set language preferences.</p></details><details><summary>Which profile images are allowed?</summary><p>JPG, PNG and WebP images up to 3 MB. Uploaded files are renamed securely and executable file types are blocked.</p></details><details><summary>Can I change my password?</summary><p>Yes. Open Profile, enter the current password and choose a new password containing at least eight characters.</p></details></section>
<section id="reservations" class="faq-group reveal-cinema"><div class="section-tag">Seats & reservations</div><details><summary>How does automatic best-seat selection work?</summary><p>The server searches available seats in the preferred class, prioritizing contiguous positions close to the centre of a row.</p></details><details><summary>Can another customer take seats in my cart?</summary><p>Active seats are protected by database-backed holds until the displayed timer expires or you remove them.</p></details><details><summary>What happens when the timer expires?</summary><p>The cart is abandoned and its holds are removed automatically, returning those seats to live availability.</p></details></section>
<section id="checkout" class="faq-group reveal-cinema"><div class="section-tag">Cart & checkout</div><details><summary>Can one cart contain multiple movies?</summary><p>Yes. MoviePro groups seats from multiple shows into one checkout and creates individual bookings under one order.</p></details><details><summary>Which payment methods are included?</summary><p>Demo Card, JazzCash, Easypaisa and pay-at-cinema methods. Real gateway credentials are not included in this academic build.</p></details><details><summary>Can I add snacks?</summary><p>Available concessions and combos can be added to the cart. Stock is checked again inside the checkout transaction.</p></details></section>
<section id="tickets" class="faq-group reveal-cinema"><div class="section-tag">Tickets & bookings</div><details><summary>Where do I find confirmed tickets?</summary><p>Open My Bookings or your Profile activity panel and select a booking reference. Each ticket includes movie, show, seats, amount and QR code.</p></details><details><summary>Can I print the ticket?</summary><p>Yes. Ticket and invoice screens include print-friendly styles and controls.</p></details><details><summary>What happens after cancellation?</summary><p>The booking status changes, booked seats are released, show availability is restored and related reward/payment adjustments are applied where configured.</p></details></section>
<section id="rewards" class="faq-group reveal-cinema"><div class="section-tag">Rewards & offers</div><details><summary>How are CinePoints earned?</summary><p>Points are calculated from the confirmed order total using the commerce settings configured by the administrator.</p></details><details><summary>Can points and promo codes be used together?</summary><p>Yes, subject to configured redemption limits. Checkout calculates coupon discount, loyalty discount, fees and tax in a consistent server-side order.</p></details><details><summary>Where can administrators change rates?</summary><p>Admin Settings controls booking-fee percentage, sales tax, loyalty value and redemption limits.</p></details></section>
</div></div></section>
<section class="section section-alt"><div class="container"><div class="content-cta reveal-cinema"><div><div class="section-tag">Still need help?</div><h2>Send the MoviePro team a message.</h2><p>Include your booking or order reference so support can understand the issue quickly.</p></div><a class="btn btn-primary magnetic" href="<?= url('contact.php') ?>">Contact support</a></div></div></section>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
